### ISSUE TITLE
CDK Synth throws error unable to find index.ts

### ISSUE THREAD

**Issue by dmccorm2** [devops-at-home/cdk-iot-core-certificates#68]
https://github.com/devops-at-home/cdk-iot-core-certificates/blob/bf78f29f8ec90aa55c83bb1c433354595b3e52ef/src/index.ts#L45

When I follow the example and run `cdk synth` I get the following error:
`Error: cannot find entry file at ./node_modules/cdk-iot-core-certificates/lib/lambda/index.ts`

However when I change the index file in your src custom lambda handler to `index.js` instead, CDK synth works fine.

Should this be changed?

**Comment by devops-at-home** [comment]
Hello

Thank you for your interest in my project and also for providing an easy to follow description of the problem. This bug is now fixed in version `1.0.64` and onwards on NPM.

I've also created an integration tests repo so these kinds of bugs will be detected early in future.

https://github.com/devops-at-home/cdk-integration-tests

This bug seemed like an easy one on the surface but getting Projen to do what I wanted it to do was challenging as you can tell by the history on this issue. For now I am still using the `NodejsFunction` L3 Construct but I would like to switch to the Projen native pre-bundling in a later release. For this release I could get it working locally but no luck with Github Actions.

https://github.com/projen/projen/pull/1070
